const {w: t} = require('core/i18n');

module.exports = {
  'js.topSearch.recentObjects': t('Recent objects'),
  'js.topSearch.foundMenuNodes': t('Found menu items'),
  'js.topSearch.recentMenuNodes': t('Recent menu items'),
  'js.cryptopro.notloaded': t('CryptoPro plugin is not available.'),
  'js.cryptopro.failopen': t('Failed to open certificates storage!'),
  'js.cryptopro.failclose': t('Failed to close certificates storage!'),
  'js.cryptopro.wrongcontent': t('Inapropriate data obtained for signing: \'%contentType\''),
  'js.cryptopro.noplugin': t('Digital sign plugin not loaded'),
  'js.cryptopro.nocert' : t('Certificate not found!'),
  'js.cryptopro.nocerts' : t('No certificates for signing!'),
  'js.cryptopro.nodata': t('Failed to get data for signing!'),
  'js.cryptopro.busy': t('Failed to sign data. Signing module is busy.'),
  'js.cryptopro.wrongstatus': t('Signature sending failed, error code: \'%status\''),
  'js.cryptopro.wrongtype': t('Signature sending failed: invalid response type \'%type\''),
  'js.cryptopro.servererror': t('Signature sending failed: server responded \'%message\''),
  'js.cryptopro.failgetcert' : t('Failed to obtain certificate object!'),
  'js.cryptopro.failmakesign' : t('Signing failed!'),
  'js.cryptopro.failgetcertsign' : t('Failed to get certificate!'),
  'js.common.mb': t('Mb'),
  'js.common.kb': t('Kb'),
  'js.common.byte': t('byte'),
  'js.common.dt.processing': t('Wait...'),
  'js.common.dt.search': t('Search:'),
  'js.common.dt.lengthMenu': t('Show by _MENU_'),
  'js.common.dt.info': t('Records from _START_ to _END_ of _TOTAL_ records'),
  'js.common.dt.infoEmpty': t('Records from 0 to 0 of 0 records'),
  'js.common.dt.infoFiltered': t('(total _MAX_)'),
  'js.common.dt.infoPostFix': t(' '),
  'js.common.dt.loadingRecords': t('Loading...'),
  'js.common.dt.zeroRecords': t('No data.'),
  'js.common.dt.emptyTable': t('Table has no data'),
  'js.common.dt.paginate.first': t('<<'),
  'js.common.dt.paginate.previous': t('<'),
  'js.common.dt.paginate.next': t('>'),
  'js.common.dt.paginate.last': t('>>'),
  'js.common.dt.aria.sortAscending': t(': activate for sorting by ascending order'),
  'js.ajaxUploader.tooSmall': t('Minimum file size - {limit}'),
  'js.ajaxUploader.tooBig': t('Maximum file size - {limit}'),
  'js.ajaxUploader.wrongExtension': t('Allowed only: {extensions}'),
  'js.ajaxUploader.wrongMimeType': t('Allowed only: {mimeTypes}'),
  'js.ajaxUploader.notImage': t('File is not an image.'),
  'js.ajaxUploader.overHeight': t('Max height - {limit} px.'),
  'js.ajaxUploader.overWidth': t('Max width - {limit} px.'),
  'js.ajaxUploader.underHeight': t('Min height - {limit} px.'),
  'js.ajaxUploader.underWidth': t('Min width - {limit} px.'),
  'js.ajaxUploader.tooMany': t('Too many files.'),
  'js.ajaxUploader.alreadyExists': t('This file is already uploaded.'),
  'js.calendar.days.sunday': t('Sunday'),
  'js.calendar.days.monday': t('Monday'),
  'js.calendar.days.tuesday': t('Tuesday'),
  'js.calendar.days.wednesday': t('Wednesday'),
  'js.calendar.days.thursday': t('Thursday'),
  'js.calendar.days.friday': t('Friday'),
  'js.calendar.days.saturday': t('Saturday'),
  'js.calendar.daysShort.sunday': t('Sun'),
  'js.calendar.daysShort.monday': t('Mon'),
  'js.calendar.daysShort.tuesday': t('Tue'),
  'js.calendar.daysShort.wednesday': t('Wed'),
  'js.calendar.daysShort.thursday': t('Thu'),
  'js.calendar.daysShort.friday': t('Fri'),
  'js.calendar.daysShort.saturday': t('Sat'),
  'js.calendar.daysMin.sunday': t('Su'),
  'js.calendar.daysMin.monday': t('Mo'),
  'js.calendar.daysMin.tuesday': t('Tu'),
  'js.calendar.daysMin.wednesday': t('We'),
  'js.calendar.daysMin.thursday': t('Th'),
  'js.calendar.daysMin.friday': t('Fr'),
  'js.calendar.daysMin.saturday': t('Sa'),
  'js.calendar.months.january': t('January'), 
  'js.calendar.months.february': t('Februray'),
  'js.calendar.months.march': t('March'),
  'js.calendar.months.april': t('April'),
  'js.calendar.months.may': t('May'),
  'js.calendar.months.june': t('June'),
  'js.calendar.months.july': t('July'),
  'js.calendar.months.august': t('August'),
  'js.calendar.months.september': t('September'),
  'js.calendar.months.october': t('October'),
  'js.calendar.months.november': t('November'),
  'js.calendar.months.december': t('December'),
  'js.calendar.monthsShort.january': t('Jan'),
  'js.calendar.monthsShortdays.february': t('Feb'),
  'js.calendar.monthsShortdays.march': t('Mar'),
  'js.calendar.monthsShortdays.april': t('Apr'),
  'js.calendar.monthsShortdays.may': t('May'),
  'js.calendar.monthsShortdays.june': t('Jun'),
  'js.calendar.monthsShortdays.july': t('Jul'),
  'js.calendar.monthsShortdays.august': t('Aug'),
  'js.calendar.monthsShortdays.september': t('Sen'),
  'js.calendar.monthsShortdays.october': t('Oct'),
  'js.calendar.monthsShortdays.november': t('Nov'),
  'js.calendar.monthsShortdays.december': t('Dec'),
  'js.calendar.editEvent': t('Edit'),
  'js.calendar.deleteEvent': t('Delete event'),
  'js.calendar.deleteSchedule': t('Delete schedule'),
  'js.calendar.wrongSettings': t('Bad event setup'),
  'js.calendar.eachone': t('Each'),
  'js.calendar.each': t('Each'),
  'js.calendar.eachn': t('Each'),
  'js.calendar.eachm': t('Eeach'),
  'js.calendar.skipeachone': t('Excluding each'),
  'js.calendar.skipeachn': t('Excluding each'),
  'js.calendar.skipeachm': t('Excluding each'),
  'js.calendar.year': t(' year'),
  'js.calendar.years1': t(' year'),
  'js.calendar.years2': t(' years'),
  'js.calendar.someYears': t('%s %f, %m1 %w, in %m2'),
  'js.calendar.skipped': t('Excluding %s'),
  'js.calendar.weekday': t(', if %d'),
  'js.calendar.everyYear': t('%s %m1, %d day of %w, in %m2'),
  'js.calendar.everyMonth': t('%s %d day of %w, in %m'),
  'js.calendar.everyWeek': t('%s %d, in %m'),
  'js.calendar.everyDay': t('%s day, in %m'),
  'js.calendar.everyHour': t('%s hour, on %min minute and %sec second'),
  'js.calendar.everyMinute': t('%s minute on %sec second'),
  'js.calendar.during': t('during'),
  'js.calendar.h': t(' h'),
  'js.calendar.m': t(' m'),
  'js.calendar.s': t(' s'),
  'js.geobuilder.confirmImport': t('Import geo-json to map?'),
  'js.geobuilder.deleteAll': t('Delete all'),
  'js.geobuilder.confirmDeleteAll': t('Delete all objects?'),
  'js.geobuilder.center': t('Center by objects'),
  'js.geobuilder.invalidJson': t('Invalid object JSON'),
  'js.geobuilder.unknownType': t('Unknown geometry type'),
  'js.geobuilder.invalidGeoJson': t('Invalid geo json'),
  'js.geobuilder.point': t('Mark'),
  'js.geobuilder.line': t('Line'),
  'js.geobuilder.polygon': t('Polygon'),
  'js.geobuilder.circle': t('Circle'),
  'js.geocoord.contentHeader': t('Coordinates&nbsp&nbsp'),
  'js.geocoord.set': t('Set'),
  'js.geocoord.invalidcoord': t('Ymap: Invalid geo coords'),
  'js.geocoord.warning': t('Warning: Host protocol is secure. Geojson validation is not perfomed'),
  'js.geocoord.created': t('created'),
  'js.geocoord.changed': t('edited'),
  'js.geocoord.attr': t('Attribute'),
  'js.geocoord.newattr': t('New value'),
  'js.geocoord.byUser': t('by user'),
  'js.manager.formAlert': t('Object was opened directly, there is no source list. Go to <a href=\'/\'><b>default page</b></a>.'),
  'js.manager.reloadConfirm': t('Unsaved changes will be lost. Refresh?'),
  'js.manager.certTitle': t('%sub, issued on %issue, valid from %d1 to %d2'),
  'js.manager.cadesFail': t('Failed to load signing plugin.'),
  'js.manager.wf': t('Workflow'),
  'js.manager.confirm': t('Are you sure?'),
  'js.manager.confirmClose': t('Delete object?'),
  'js.manager.signFail': t('Signing error'),
  'js.manager.signSuccess': t('Action signed!'),
  'js.manager.cryptoFail': t('Crypto Pro failed to sign data. Check license please.'),
  'js.manager.error': t('Error'),
  'js.manager.done': t('Done!'),
  'js.manager.objectCreated': t('Object created'),
  'js.manager.requiredField': t('Field is required'),
  'js.manager.formErrors': t('Fix errors in form'),
  'js.manager.objectLock': t('<b>Object is used by user <i>%name</i>. Form is read only mode.</b><br>'),
  'js.manager.signChange': t('Signed data was changed.'),
  'js.manager.signCheck': t('Check sign'),
  'js.manager.subject': t('Subject'),
  'js.manager.issuer': t('Provider'),
  'js.manager.validSince': t('Valid from'),
  'js.manager.validTill': t('Valid to'),
  'js.manager.serial': t('Serial'),
  'js.manager.signNotValid': t('Signature is invalid!'),
  'js.manager.signValid': t('Signature is valid'),
  'js.manager.cryptoNotInstalled': t('CryptoPRO plugin not installed'),
  'js.manager.notValidMask': t('Inaproperiate value (does not match input mask)'),
  'js.manager.loading': t('Uploading to server...'),
  'js.manager.loaded': t('Uploaded'),
  'js.manager.loadFail': t('File uploading error'),
  'js.manager.deleteLoaded': t('Delete uploaded file?'),
  'js.manager.deleteRef': t('Delete object from reference?'),
  'js.manager.noData': t('No data'),
  'js.manager.noDataMessage': t('No results found for current clarification conditions.'),
  'js.refShortView.unknownType': t('RefShortView: Unknown attribute type: %type'),
  'js.worktime.notFilled': t('Schedule not filled.'),
  'js.worktime.break': t(' (break %time)'),
  'js.worktime.schedule': t('Week schedule'),
  'js.worktime.formatTime': t(' from %h1:%m1 to %h2:%m2'),
  'js.filter.select': t('Select filter...'),
  'js.filter.eq': t('= equal'),
  'js.filter.earlier': t('before'),
  'js.filter.less': t('less'),
  'js.filter.later': t('after'),
  'js.filter.more': t('more'),
  'js.filter.oreq': t(' or equal'),
  'js.filter.filter': t('Filter'),
  'js.inlineFormCell.required': t('Required field'),
  'js.inlineFormCell.notValidMask': t('Value does not match input mask'),
  'js.inlineFormCell.deleteFromRef': t('Delete selected object from reference?'),
  'js.inlineForm.deleteFromCol': t('Remove object from collection?'),
  'js.inlineForm.removeError': t('Error when removing object.'),
  'js.inlineForm.confirmDelete': t('Delete object?'),
  'js.inlineForm.confirm': t('Are you sure?'),
  'js.listManager.initError': t('List initialization error.'),
  'js.listManager.accessDenied': t('Access denied!'),
  'js.listManager.errData': t('Data fetch error.'),
  'js.listManager.breakRef': t('<p>Object selected by reference \'%cap\' is linked to <a href=\'%href\'>another object</a>.</p><p>Are you sure, you want to break this link?</p>'),
  'js.listManager.breakRefRef': t('<p>Object selected by reference \'%cap\' is linked to <a href=\'%href\'>%name</a>.</p><p>Are you sure, you want to break this link?</p>'),
  'js.listManager.warn': t('Warning!'),
  'js.listManager.yes': t('Yes'),
  'js.listManager.no': t('No'),
  'js.listManager.itemErr': t('Error on object fetch'),
  'js.listManager.sortErr': t('Error of object sorting'),
  'js.listManager.delErr': t('Error og object deletion'),
  'js.listManager.confirmDelItemsCol': t('Remove selected objects from collection?'),
  'js.listManager.confirmDelItems': t('Delete selected objects?'),
  'js.listManager.initColErr': t('Collection initialization error: %cap')
}
