const {w: t} = require('core/i18n');

module.exports = {
  'templates.default.home': t('Home'),
  'templates.default.login': t('Login'),
  'templates.default.password': t('Password'),
  'templates.default.repeatPwd': t('Password repeat'),
  'templates.default.enter': t('Sign in'),
  'templates.default.main': t('Home'),
  'templates.default.login.title': t('Signing in'),
  'templates.default.login.register': t('Sign up'),
  'templates.default.login.signin': t('Sign in'),
  'templates.default.profile.title': t('User %name profile'),
  'templates.default.profile.save': t('Save'),
  'templates.default.profile.back': t('Back to application'),
  'templates.default.register.title': t('Signing up'),
  'templates.default.register.register': t('Sign up'),
  'templates.default.changePwd.title': t('Setting password for user %name'),
  'templates.default.changePwd.changePwd': t('Change password'),
  'templates.default.attrs.del': t('Delete'),
  'templates.default.attrs.up': t('Up'),
  'templates.default.attrs.down': t('Down'),
  'templates.default.attrs.update': t('Edit'),
  'templates.default.attrs.save': t('Save'),
  'templates.default.attrs.cancel': t('Cancel'),
  'templates.default.attrs.remove': t('Remove'),
  'templates.default.attrs.fileFrame.done': t('File uploaded'),
  'templates.default.attrs.imageFrame.done': t('Image uploaded'),
  'templates.default.attrs.calendar.jan': t('January'),
  'templates.default.attrs.calendar.feb': t('February'),
  'templates.default.attrs.calendar.mar': t('March'),
  'templates.default.attrs.calendar.apr': t('April'),
  'templates.default.attrs.calendar.may': t('May'),
  'templates.default.attrs.calendar.jun': t('June'),
  'templates.default.attrs.calendar.jul': t('July'),
  'templates.default.attrs.calendar.aug': t('August'),
  'templates.default.attrs.calendar.sep': t('September'),
  'templates.default.attrs.calendar.oct': t('October'),
  'templates.default.attrs.calendar.nov': t('November'),
  'templates.default.attrs.calendar.dec': t('December'),
  'templates.default.attrs.calendar.year': t('Year'),
  'templates.default.attrs.calendar.schedule': t('Schedule'),
  'templates.default.attrs.calendar.description': t('Description'),
  'templates.default.attrs.calendar.event': t('Event'),
  'templates.default.attrs.calendar.events': t('Events'),
  'templates.default.attrs.calendar.type': t('Type'),
  'templates.default.attrs.calendar.skip': t('Exclusion'),
  'templates.default.attrs.calendar.skips': t('Exclusions'),
  'templates.default.attrs.calendar.exception': t('Exception'),
  'templates.default.attrs.calendar.month': t('Month'),
  'templates.default.attrs.calendar.weekday': t('Weekday'),
  'templates.default.attrs.calendar.day': t('Day'),
  'templates.default.attrs.calendar.hour': t('Hour'),
  'templates.default.attrs.calendar.min': t('Minute'),
  'templates.default.attrs.calendar.sec': t('Second'),
  'templates.default.attrs.calendar.add': t('Add'),
  'templates.default.attrs.calendar.cancel': t('Cancel'),
  'templates.default.attrs.calendar.eventSave': t('Save event'),
  'templates.default.attrs.calendar.schSave': t('Save schedule'),
  'templates.default.attrs.date': t('Date'),
  'templates.default.attrs.datetime': t('Date and time'),
  'templates.default.attrs.objectListLink.open': t('Open'),
  'templates.default.attrs.file.del': t('Delete file'),
  'templates.default.attrs.file.drop': t('Drag file here'),
  'templates.default.attrs.file.choose': t('or find file in folder'),
  'templates.default.attrs.file.overflow': t('Too many files'),
  'templates.default.attrs.file.file': t('File'),
  'templates.default.attrs.file.wait': t('Waiting for check...'),
  'templates.default.attrs.geobuilder.create': t('Create geo-objects'),
  'templates.default.attrs.geobuilder.edit': t('Edit geo-objects'),
  'templates.default.attrs.geobuilder.title': t('Geo-objects constructor'),
  'templates.default.attrs.geobuilder.success': t('Finish'),
  'templates.default.attrs.geobuilder.export': t('Export'),
  'templates.default.attrs.geobuilder.exportTitle': t('Map to text'),
  'templates.default.attrs.geobuilder.import': t('Import'),
  'templates.default.attrs.geobuilder.importTitle': t('Text to map'),
  'templates.default.attrs.geobuilder.data': t('Data in GEO-JSON format'),
  'templates.default.attrs.geobuilder.error': t('Invalid data...'),
  'templates.default.attrs.geocoord.create': t('Create coordinates'),
  'templates.default.attrs.geocoord.edit': t('Change coordinates'),
  'templates.default.attrs.geocoord.title': t('Set coordinates'),
  'templates.default.attrs.geocoord.success': t('Save'),
  'templates.default.attrs.geocoord.search': t('Enter address...'),
  'templates.default.attrs.geocoord.noCoordError': t('Cordinates not found'),
  'templates.default.attrs.geocoord.data': t('Enter data in GEO-JSON format'),
  'templates.default.attrs.geocoord.verify': t('Check and display in GEO-JSON'),
  'templates.default.attrs.geocoord.dataError': t('Invalid data...'),
  'templates.default.attrs.multifile.drop': t('Drag files here'),
  'templates.default.attrs.period.date': t('Date'),
  'templates.default.attrs.referenceHeader.displayValueReadOnly': t('Value inacessible'),
  'templates.default.attrs.referenceHeader.displayValue': t('Object will be linked automatically'),
  'templates.default.attrs.schedule.mon': t('Mo'),
  'templates.default.attrs.schedule.tue': t('Tu'),
  'templates.default.attrs.schedule.wed': t('We'),
  'templates.default.attrs.schedule.thu': t('Th'),
  'templates.default.attrs.schedule.fri': t('Fr'),
  'templates.default.attrs.schedule.sat': t('Sa'),
  'templates.default.attrs.schedule.sun': t('Su'),
  'templates.default.attrs.schedule.fivedays': t('Five days'),
  'templates.default.attrs.schedule.daily': t('Daily'),
  'templates.default.attrs.schedule.worktime': t('Work time'),
  'templates.default.attrs.schedule.break': t('Break'),
  'templates.default.attrs.selectGroup.accept': t('Accept'),
  'templates.default.attrs.selectGroup.close': t('Close'),
  'templates.default.errors.403': t('Access denied'),
  'templates.default.errors.403.detail': t('Sorry, but access to this resource is restricted.'),
  'templates.default.errors.404': t('Page not found'),
  'templates.default.errors.404.detail': t('We could not find the page you are looking for.'),
  'templates.default.errors.500': t('Server error'),
  'templates.default.errors.500.title': t('Something went wrong'),
  'templates.default.errors.500.detail': t('We are working on fixing this issue right now.'),
  'templates.default.errors.search': t('Search...'),
  'templates.default.layout.footer.version': t('Version'),
  'templates.default.layout.footer.copyright': t('Copyright'),
  'templates.default.layout.header.userAvatar': t('User avatar'),
  'templates.default.layout.header.profile': t('User profile'),
  'templates.default.layout.header.chpwd': t('Change password'),
  'templates.default.layout.header.signOut': t('Sign out'),
  'templates.default.layout.header.filters': t('Filters'),
  'templates.default.layout.header.search': t('Search...'),
  'templates.default.layout.header.clearSearch': t('Clear search field'),
  'templates.default.layout.topMenu.more': t('More'),
  'templates.default.utils.imageUploader.drop': t('Drag image here'),
  'templates.default.utils.imageUploader.modal.del': t('Delete file'),
  'templates.default.utils.imageUploader.modal.sharing': t('Sharing'),
  'templates.default.utils.imageUploader.modal.link': t('Link'),
  'templates.default.utils.imageUploader.modal.extLink': t('External link'),
  'templates.default.utils.imageUploader.modal.shareLink': t('Share link'),
  'templates.default.utils.imageUploader.modal.close': t('Close'),
  'templates.default.view.export.title': t('Export'),
  'templates.default.view.history.title': t('Object change log'),
  'templates.default.view.history.close': t('Close'),
  'templates.default.view.history.refresh': t('Refresh'),
  'templates.default.view.collection.chooseObject': t('Select one object for editiing.'),
  'templates.default.view.collection.add': t('Add'),
  'templates.default.view.collection.create': t('Create'),
  'templates.default.view.collection.edit': t('Edit'),
  'templates.default.view.collection.delete': t('Delete'),
  'templates.default.view.collection.close': t('Close'),
  'templates.default.view.collection.refresh': t('Refresh'),
  'templates.default.view.collection.selectFilter': t('Select filter...'),
  'templates.default.view.collection.createFilter': t('Create filter'),
  'templates.default.view.collection.updateFilter': t('Edit filter'),
  'templates.default.view.collection.resetFilter': t('Reset filter'),
  'templates.default.view.collection.selectColumn': t('Select field...'),
  'templates.default.view.collection.selectDate': t('Select date...'),
  'templates.default.view.collection.selectNumber': t('Enter number...'),
  'templates.default.view.collection.selectValue': t('Enter value...'),
  'templates.default.view.collection.success': t('Add condition'),
  'templates.default.view.collection.apply': t('Apply filter'),
  'templates.default.view.collection.allClasses': t('To all classes'),
  'templates.default.view.collection.filterName': t('Add filter name...'),
  'templates.default.view.collection.saveFilterTitle': t('Save filter'),
  'templates.default.view.collection.saveFilter': t('Save'),
  'templates.default.view.collection.delFilter': t('Delete filter'),
  'templates.default.view.collection.editFilter': t('Edit'),
  'templates.default.view.collection.operation.max': t('max'),
  'templates.default.view.collection.operation.min': t('min'),
  'templates.default.view.collection.operation.eq': t('equal'),
  'templates.default.view.collection.operation.in': t('contains'),
  'templates.default.view.collection.exportParams.export': t('Export'),
  'templates.default.view.collection.exportParams.close': t('Close'),
  'templates.default.view.collection.exportParams.error': t('Failed to start export!'),
  'templates.default.view.dashboard.title': t('Dashboard'),
  'templates.default.view.item.createByRef': t('Creation of object for reference \'%prop\' of object \'%item\''),
  'templates.default.view.item.createByCol': t('Creation of object in collection \'%prop\' of object \'%item\''),
  'templates.default.view.item.crypto.choose': t('Select certificate for signing'),
  'templates.default.view.item.crypto.info': t('View certificate info'),
  'templates.default.view.item.crypto.cancel': t('Cancel'),
  'templates.default.view.item.crypto.select': t('Select'),
  'templates.default.view.item.crypto.subject': t('Subject'),
  'templates.default.view.item.crypto.provider': t('Provider'),
  'templates.default.view.item.crypto.validSince': t('Valid from'),
  'templates.default.view.item.crypto.validTill': t('Valid to'),
  'templates.default.view.item.crypto.serial': t('Serial'),
  'templates.default.view.item.crypto.close': t('Close'),
  'templates.default.view.item.createAnother': t('Create more'),
  'templates.default.view.item.close': t('Close'),
  'templates.default.view.item.reload': t('Refresh'),
  'templates.default.view.item.history': t('Changelog'),
  'templates.default.view.item.signStatus': t('Sign status'),
  'templates.default.view.item.confirm': t('Confirm your actions'),
  'templates.default.view.item.continue': t('Continue'),
  'templates.default.view.item.cancel': t('Cancel'),
  'templates.default.view.selectClass.title': t('Create'),
  'templates.default.view.selectClass.submit': t('Submit'),
  'templates.default.view.list.select': t('Select'),
  'templates.default.view.list.close': t('Close'),
  'templates.default.view.list.edit': t('Edit'),
  'templates.default.view.list.save': t('Save'),
  'templates.default.view.list.cancel': t('Cancel'),
  'templates.default.view.list.preTitle': t('Attribute \'%prop\' of object \'%item\' value selection'),
  'templates.default.view.listShort.view': t('View'),
  'templates.default.view.listShort.close': t('Close'),
  'templates.default.view.listShort.reload': t('Refresh'),
  'templates.default.view.listFilter.helper': t('Query syntax'),
  'templates.default.view.listFilter.title': t('List filter'),
  'templates.default.view.listFilter.defaultOption': t('Select filter...'),
  'templates.default.view.listFilter.assignFilter': t('Apply filter'),
  'templates.default.view.listFilter.removeFilter': t('Delete filter'),
  'templates.default.view.listFilter.saveFilter': t('Save'),
  'templates.default.view.listFilter.allClasses': t('For all classes'),
  'templates.default.view.listFilter.filterName': t('Enter filter name...'),
  'templates.default.view.listFilter.createFilter': t('Create filter'),
  'templates.default.view.listFilter.editFilter': t('Edit filter'),
  'templates.default.view.listFilter.resetFilter': t('Reset filter'),
  'templates.default.view.listFilterHelper': t('Create filter by entering query string as follows:<br>`Name` = \'Ivan\', where `Name` is attribute name (selected from dropdown list) and \'Ivan\' is a string value<br>To specify reference value, you can use dereference as follows `Person`.`Name` = \'Ivan\'<br>Several values can be specified with logical operators<br><li><ul>and - match all values</ul><ul>or - match any value</ul></li>')
}
